Vamos a cubrir `String, Tuple, NamedTuple, UnitRange, Arrays, Pair, Dict, Symbol`.

***Operadores de broadcasting y funciones***

In [1]:
[1, 2, 3] .+ 1

3-element Vector{Int64}:
 2
 3
 4

In [7]:
# Funciona automáticamente con funciones
log.([1, 2, 3],10)

3-element Vector{Float64}:
 Inf
  3.3219280948873626
  2.095903274289385

Es una convención en Julia agregar un `!` a los nombres de funciones que modifican uno o más de sus argumentos. 

In [8]:
function add_one!(V)
    for i in eachindex(V)
        V[i] += 1
    end
    return nothing
end

add_one! (generic function with 1 method)

In [9]:
my_data = [1, 2, 3]
add_one!(my_data)

In [10]:
my_data

3-element Vector{Int64}:
 2
 3
 4

***String***

In [11]:
typeof("This is a string")

String

In [15]:
text = """
        This is a big multiline string with a nested "quotation".
        As you can see.
        It is still a String to Julia
        """

"This is a big multiline string with a nested \"quotation\".\nAs you can see.\nIt is still a String to Julia\n"

***Concatenación de strings***

In [20]:
hello = "Hello"
goodbye = "Goodbye"
hello * " " * goodbye

"Hello Goodbye"

In [21]:
# Esto es equivalente a
join([hello, goodbye]," ")

"Hello Goodbye"

***Interpolación de strings***

In [22]:
function test_interpolated(a,b)
    if a < b
        "$a is less than $b"
    elseif a > b 
        "$a is greater than $b"
    else
        "$a is equal to $b"
    end
end    

test_interpolated (generic function with 1 method)

In [24]:
test_interpolated(3.14,3.14)

"3.14 is equal to 3.14"

***Manipulación de strings***

In [25]:
julia_string = "Julia is an amazing open source programming language"

"Julia is an amazing open source programming language"

In [26]:
contains(julia_string, "Julia")

true

In [27]:
startswith(julia_string, "Julia")

true

In [28]:
endswith(julia_string, "Julia")

false

In [29]:
lowercase(julia_string)

"julia is an amazing open source programming language"

In [30]:
uppercase(julia_string)

"JULIA IS AN AMAZING OPEN SOURCE PROGRAMMING LANGUAGE"

In [31]:
titlecase(julia_string)

"Julia Is An Amazing Open Source Programming Language"

In [32]:
lowercasefirst(julia_string)

"julia is an amazing open source programming language"

In [33]:
# replace() necesita que le pasemos un string y una nueva sintaxis, llamada par
replace(julia_string, "amazing" => "awesome")

"Julia is an awesome open source programming language"

In [34]:
split(julia_string, " ")

8-element Vector{SubString{String}}:
 "Julia"
 "is"
 "an"
 "amazing"
 "open"
 "source"
 "programming"
 "language"

***Conversiones a String***

In [35]:
typeof(string(123))

String

Para convertir un string a un número, Julia tiene la función `parse`.

In [37]:
typeof(parse(Int64,"123"))

Int64

In [43]:
# Esto devuelve nothing
tryparse(Int64, "Hello World")

***Tuplas***
Una tupla es un container de longitud fija que puede contener tipos de datos múltiples. Es _inmutable_, no puede ser modificado después de ser instanciado.

In [44]:
my_tuple = (1, 3.14, "Julia")

(1, 3.14, "Julia")

In [45]:
my_tuple[2]

3.14

In [46]:
# Puedo pasar a una función anónima más de una variable mediante el uso de tuplas
map((x,y) -> x^y, 2, 3)

8

In [48]:
map((x, y, z) -> x^y + z, 3, 2, 1)

10

***Tupla nombrada***

Al igual que las tuplas, tiene elementos de distintos tipos y es inmutable. Pero ahora sus elementos pueden tener un nombre.

In [49]:
my_namedtuple = (i=1, f=3.14, s="Julia")

(i = 1, f = 3.14, s = "Julia")

In [50]:
my_namedtuple.s

"Julia"

In [51]:
# Pueden ser construidas instanciando sus elementos por fuera
i = 1
f = 3.14
s = "Julia"

my_quick_namedtuple = (; i, f, s)

(i = 1, f = 3.14, s = "Julia")

***Rangos***

In [52]:
1:10

1:10

In [53]:
typeof(1:10)

UnitRange{Int64}

In [55]:
# Los podemos agarrar en un array
[x for x in 1:10]

10-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [56]:
typeof(1.0:10.0)

StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}

In [59]:
[x for x in 0:2:10]

6-element Vector{Int64}:
  0
  2
  4
  6
  8
 10

***Array***

In [60]:
myarray = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [61]:
# También puede contener distintos data-types
myarray = ["text", 1, :symbol]

3-element Vector{Any}:
  "text"
 1
  :symbol

El constructor de bajo nivel de los arrays de Julia es el constructor default. Acepta el data-type dentro de las llaves y dentro del constructor se pasa el tipo de elemento, junto con las dimensiones desadas. Es usual inicializar vectores y matrices con elementos indefinidos usando el argumento `undef`.

In [62]:
my_vector = Vector{Float64}(undef, 10)

10-element Vector{Float64}:
   6.9368173568973e-310
   6.93681702732233e-310
   6.9368173569724e-310
   6.9368170273097e-310
   6.93681735686175e-310
   6.9368618040029e-310
   3.1783e-320
 NaN
   3.237914e-318
   6.9368664085109e-310

In [63]:
my_matrix = Matrix{Float64}(undef, 10, 2)

10×2 Matrix{Float64}:
 6.93685e-310  6.93685e-310
 6.93685e-310  6.93685e-310
 6.93685e-310  6.93685e-310
 6.93685e-310  6.93685e-310
 6.93685e-310  6.93685e-310
 6.93685e-310  6.93685e-310
 6.93685e-310  6.93685e-310
 6.93685e-310  6.93685e-310
 6.93685e-310  6.93685e-310
 6.93685e-310  6.93685e-310

In [64]:
my_vector_zeros = zeros(10)

10-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [65]:
my_matrix_zeros = zeros(Int64,10,2)

10×2 Matrix{Int64}:
 0  0
 0  0
 0  0
 0  0
 0  0
 0  0
 0  0
 0  0
 0  0
 0  0

In [67]:
my_matrix_ones = ones(10,2)

10×2 Matrix{Float64}:
 1.0  1.0
 1.0  1.0
 1.0  1.0
 1.0  1.0
 1.0  1.0
 1.0  1.0
 1.0  1.0
 1.0  1.0
 1.0  1.0
 1.0  1.0

In [68]:
my_matrix_π = Matrix{Float64}(undef, 2, 2)
fill!(my_matrix_π, 3.14)

2×2 Matrix{Float64}:
 3.14  3.14
 3.14  3.14

In [75]:
Float64[[1 2]
 [3 4]]

2×2 Matrix{Float64}:
 1.0  2.0
 3.0  4.0

In [76]:
Bool[0 1 0 1]

1×4 Matrix{Bool}:
 0  1  0  1

Se puede hacer _mix_ y _match_ con los arrays haciendo uso de los constructores.

In [77]:
[ones(Int, 2, 2) zeros(Int, 2, 2)]

2×4 Matrix{Int64}:
 1  1  0  0
 1  1  0  0

In [78]:
[zeros(Int, 2, 2)
 ones(Int, 2, 2)]

4×2 Matrix{Int64}:
 0  0
 0  0
 1  1
 1  1

In [79]:
[ones(Int, 2, 2) [1; 2]
 [3 4]            5]

3×3 Matrix{Int64}:
 1  1  1
 1  1  2
 3  4  5

In [80]:
# Al igual que en Python hay listas de comprensión
[x^2 for x in 1:10]

10-element Vector{Int64}:
   1
   4
   9
  16
  25
  36
  49
  64
  81
 100

In [81]:
[x^y for x in 1:10 for y in 1:2]

20-element Vector{Int64}:
   1
   1
   2
   4
   3
   9
   4
  16
   5
  25
   6
  36
   7
  49
   8
  64
   9
  81
  10
 100

In [83]:
# También acepta condicionales
Float64[x^2 for x in 1:10 if isodd(x)]

5-element Vector{Float64}:
  1.0
  9.0
 25.0
 49.0
 81.0

# Me quedé en la 3.3.7.2